Signup Button Click
pamelaabreu/bundle_frontend pull request #18
Opened 2019-05-22 19:47 UTC by pamelaabreu

2019-05-22 20:40 UTC, JoshuaKGoldberg requested changes
You'll have an easier time with these kinds of validations if you use HTML attributes when possible. See the comment in `Signup.js`.

Also, a question: is this really necessary for your MVP? Do you have to validate user inputs, etc. to showcase in a demo that this works?

Since you're on a tight time budget, I'd suggest not worrying about these kinds of _"what if the user does the wrong thing?"_ concerns. Just focus on what benefits you to show in the demo, and file a note to do these later.

2019-05-22 20:40 UTC, JoshuaKGoldberg commented on src/containers/Signup/Signup.js
> +    handleSignupButtonClick = e => {
You don't have to do this in JavaScript: 

* General guide: https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation
* Example docs, for number inputs: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Validation

2019-05-22 20:41 UTC, JoshuaKGoldberg commented
Btw, if you disagree with one of my reviews, you can always dismiss it or re-request review in the UI. I'm using it to show how I would review this at work, but you definitely shouldn't be blocked on me being wrong about something. 😄 

![image](https://user-images.githubusercontent.com/3335181/58207328-7a552700-7cb0-11e9-88ae-c7fe4af7f44e.png)

2019-05-23 12:30 UTC, JoshuaKGoldberg approved these changes
LGTM! Just a couple of cleanup comments.

2019-05-23 12:30 UTC, JoshuaKGoldberg commented on src/containers/Signup/Signup.js
> +        {fillFormInputError ? <p>{fillFormInputError}</p> : null}
`fillFormInputError` is never assigned to, so you can get rid of it from here and in `state`.

2019-05-23 12:30 UTC, JoshuaKGoldberg commented on src/containers/Signup/Signup.js
> +            inputName.toLowerCase() === "username" ? false : true;
Nitpicking here: you can replace `=== "username" ? false : true` with `!== "username"`

2019-05-23 21:51 UTC, FiveEightyEight commented
Thank you for the reviews Josh!

2019-05-23 21:51 UTC, merged